/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FilesRouteImport } from './routes/files'
import { Route as HostRouteImport } from './routes/host'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as ProcessesRouteImport } from './routes/processes'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as TimersRouteImport } from './routes/timers'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ProcessesIndexRouteImport } from './routes/processes.index'
import { Route as ProcessesPidRouteImport } from './routes/processes.$pid'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesScopeUnitRouteImport } from './routes/services.$scope.$unit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessesRoute = ProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const TimersRoute = TimersRouteImport.update({
  id: '/timers',
  path: '/timers',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessesIndexRoute = ProcessesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProcessesRoute,
} as any)
const ProcessesPidRoute = ProcessesPidRouteImport.update({
  id: '/$pid',
  path: '/$pid',
  getParentRoute: () => ProcessesRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesScopeUnitRoute = ServicesScopeUnitRouteImport.update({
  id: '/$scope/$unit',
  path: '/$scope/$unit',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/files': typeof FilesRoute
  '/host': typeof HostRoute
  '/incidents': typeof IncidentsRoute
  '/jobs': typeof JobsRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/network': typeof NetworkRoute
  '/operations': typeof OperationsRoute
  '/processes': typeof ProcessesRouteWithChildren
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/terminal': typeof TerminalRoute
  '/timers': typeof TimersRoute
  '/updates': typeof UpdatesRoute
  '/users': typeof UsersRoute
  '/processes/$pid': typeof ProcessesPidRoute
  '/processes/': typeof ProcessesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/$scope/$unit': typeof ServicesScopeUnitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/files': typeof FilesRoute
  '/host': typeof HostRoute
  '/incidents': typeof IncidentsRoute
  '/jobs': typeof JobsRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/network': typeof NetworkRoute
  '/operations': typeof OperationsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/terminal': typeof TerminalRoute
  '/timers': typeof TimersRoute
  '/updates': typeof UpdatesRoute
  '/users': typeof UsersRoute
  '/processes/$pid': typeof ProcessesPidRoute
  '/processes': typeof ProcessesIndexRoute
  '/services': typeof ServicesIndexRoute
  '/services/$scope/$unit': typeof ServicesScopeUnitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/files': typeof FilesRoute
  '/host': typeof HostRoute
  '/incidents': typeof IncidentsRoute
  '/jobs': typeof JobsRoute
  '/logs': typeof LogsRoute
  '/metrics': typeof MetricsRoute
  '/network': typeof NetworkRoute
  '/operations': typeof OperationsRoute
  '/processes': typeof ProcessesRouteWithChildren
  '/security': typeof SecurityRoute
  '/services': typeof ServicesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/terminal': typeof TerminalRoute
  '/timers': typeof TimersRoute
  '/updates': typeof UpdatesRoute
  '/users': typeof UsersRoute
  '/processes/$pid': typeof ProcessesPidRoute
  '/processes/': typeof ProcessesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/$scope/$unit': typeof ServicesScopeUnitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/files'
    | '/host'
    | '/incidents'
    | '/jobs'
    | '/logs'
    | '/metrics'
    | '/network'
    | '/operations'
    | '/processes'
    | '/security'
    | '/services'
    | '/settings'
    | '/storage'
    | '/terminal'
    | '/timers'
    | '/updates'
    | '/users'
    | '/processes/$pid'
    | '/processes/'
    | '/services/'
    | '/services/$scope/$unit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/files'
    | '/host'
    | '/incidents'
    | '/jobs'
    | '/logs'
    | '/metrics'
    | '/network'
    | '/operations'
    | '/security'
    | '/settings'
    | '/storage'
    | '/terminal'
    | '/timers'
    | '/updates'
    | '/users'
    | '/processes/$pid'
    | '/processes'
    | '/services'
    | '/services/$scope/$unit'
  id:
    | '__root__'
    | '/'
    | '/files'
    | '/host'
    | '/incidents'
    | '/jobs'
    | '/logs'
    | '/metrics'
    | '/network'
    | '/operations'
    | '/processes'
    | '/security'
    | '/services'
    | '/settings'
    | '/storage'
    | '/terminal'
    | '/timers'
    | '/updates'
    | '/users'
    | '/processes/$pid'
    | '/processes/'
    | '/services/'
    | '/services/$scope/$unit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilesRoute: typeof FilesRoute
  HostRoute: typeof HostRoute
  IncidentsRoute: typeof IncidentsRoute
  JobsRoute: typeof JobsRoute
  LogsRoute: typeof LogsRoute
  MetricsRoute: typeof MetricsRoute
  NetworkRoute: typeof NetworkRoute
  OperationsRoute: typeof OperationsRoute
  ProcessesRoute: typeof ProcessesRouteWithChildren
  SecurityRoute: typeof SecurityRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  StorageRoute: typeof StorageRoute
  TerminalRoute: typeof TerminalRoute
  TimersRoute: typeof TimersRoute
  UpdatesRoute: typeof UpdatesRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processes': {
      id: '/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof ProcessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timers': {
      id: '/timers'
      path: '/timers'
      fullPath: '/timers'
      preLoaderRoute: typeof TimersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processes/': {
      id: '/processes/'
      path: '/'
      fullPath: '/processes/'
      preLoaderRoute: typeof ProcessesIndexRouteImport
      parentRoute: typeof ProcessesRoute
    }
    '/processes/$pid': {
      id: '/processes/$pid'
      path: '/$pid'
      fullPath: '/processes/$pid'
      preLoaderRoute: typeof ProcessesPidRouteImport
      parentRoute: typeof ProcessesRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$scope/$unit': {
      id: '/services/$scope/$unit'
      path: '/$scope/$unit'
      fullPath: '/services/$scope/$unit'
      preLoaderRoute: typeof ServicesScopeUnitRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ProcessesRouteChildren {
  ProcessesPidRoute: typeof ProcessesPidRoute
  ProcessesIndexRoute: typeof ProcessesIndexRoute
}

const ProcessesRouteChildren: ProcessesRouteChildren = {
  ProcessesPidRoute: ProcessesPidRoute,
  ProcessesIndexRoute: ProcessesIndexRoute,
}

const ProcessesRouteWithChildren = ProcessesRoute._addFileChildren(
  ProcessesRouteChildren,
)

interface ServicesRouteChildren {
  ServicesIndexRoute: typeof ServicesIndexRoute
  ServicesScopeUnitRoute: typeof ServicesScopeUnitRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesIndexRoute: ServicesIndexRoute,
  ServicesScopeUnitRoute: ServicesScopeUnitRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilesRoute: FilesRoute,
  HostRoute: HostRoute,
  IncidentsRoute: IncidentsRoute,
  JobsRoute: JobsRoute,
  LogsRoute: LogsRoute,
  MetricsRoute: MetricsRoute,
  NetworkRoute: NetworkRoute,
  OperationsRoute: OperationsRoute,
  ProcessesRoute: ProcessesRouteWithChildren,
  SecurityRoute: SecurityRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  StorageRoute: StorageRoute,
  TerminalRoute: TerminalRoute,
  TimersRoute: TimersRoute,
  UpdatesRoute: UpdatesRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
